version: '3.8'  # Utilise une version adaptée à tes besoins

services:
  mariadb:
    restart: always
    build:
      context: requirements/mariadb  # Contexte de construction, le dossier où se trouve le Dockerfile
      dockerfile: Dockerfile  # Spécifie le nom du Dockerfile si ce n'est pas le nom par défaut
    container_name: mariadb-ctn  # Nom du conteneur
    ports:
      - "3306:3306"  # Redirige le port 3306 de l'hôte vers le conteneur
    volumes:
      - mariadb-data:/var/lib/mysql  # Montre un volume pour persister les données
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt  # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: wp_database       # Création de la base de données WordPress
      MYSQL_USER: wp_user         # Utilisateur pour se connecter à la DB
      MYSQL_PASSWORD_FILE: /run/secrets/db_password.txt # Mot de passe pour cet utilisateur
    secrets:
      - db_password.txt
      - db_root_password.txt
    networks:
      - my-network  # Ajouter le service au réseau

  wordpress:
    restart: always
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wp-ctn
    expose:
      - "9000"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306  # Le nom du service MariaDB dans Docker
      WORDPRESS_DB_NAME: wp_database   # Le nom de la base de données
      WORDPRESS_DB_USER: wp_user # L'utilisateur MariaDB
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password.txt # Remplace par la méthode fichier si modifié

    secrets:
      - db_password.txt
    volumes:
      - wordpress-data:/var/www/html  # Le volume pour stocker les fichiers WordPress
    networks:
      - my-network

  nginx:
    restart: always
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx-ctn
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my-network
    volumes:
      - wordpress-data:/var/www/html 
    depends_on:
      - wordpress
  
volumes:
  mariadb-data:
  wordpress-data:
secrets:
  db_root_password.txt:
    file: ../secrets/db_root_password.txt
  db_password.txt:
    file: ../secrets/db_password.txt
networks:
  my-network:
    driver: bridge  # Création du réseau
